name: Run Deleter

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs
        run: |
          ALL_RUNS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/RipperHybrid/Kernel-Builder/actions/runs")
          COMPLETED_FAILED_STOPPED_RUNS=$(echo "$ALL_RUNS" | jq -r '.workflow_runs[] | select(.head_branch == "Test-2" and (.status | test("completed|failure|cancelled"))) | .id')
          echo "Old runs to delete: $COMPLETED_FAILED_STOPPED_RUNS"
          for run_id in $COMPLETED_FAILED_STOPPED_RUNS; do
            echo "Deleting run with ID: $run_id"
            curl -X DELETE -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/RipperHybrid/Kernel-Builder/actions/runs/$run_id"
          done
        shell: bash
