name: Kernel Builder

on:
  workflow_dispatch:
    inputs:
      trigger_kernel_builder:
        description: 'Flag to trigger kernel builder'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: ["LineageOS-20", "Zenitsu", "DivestOS-13", "Lava"]

    env:
      VERSION: ${{ matrix.version }}
      ARCH: arm64
      KBUILD_BUILD_HOST: Github-Action
      KBUILD_BUILD_USER: "KernelSU_Builder"
      CLANG_PATH: ${{ github.workspace }}/kernel/clang/bin
      TELEGRAM_CHAT_ID: 6211441287 # Your Telegram chat ID here

    steps:
      - name: Notify Job Start
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="New job started for version: ${{ matrix.version }}"

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout Completed
        run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Checkout Completed."
     
      - name: Setup Environment
        run: |
           sudo apt update
           sudo apt-get install -y llvm
           sudo apt install -y python3-pip jq libarchive-tools zip lib32z-dev libghc-bzlib-dev pngcrush ^liblzma.* python-is-python3 libsdl1.2-dev autoconf libxml2-utils wget pkg-config unzip w3m gawk imagemagick libc6-dev gcc-multilib patchelf gzip clang subversion optipng device-tree-compiler ccache gcc ^liblz4-.* lzip rsync automake fastboot python2.7 patch zip pngquant expat lzop libswitch-perl make libcap-dev python2 adb libxml2 bison libxml-simple-perl zlib1g-dev libarchive-tools libtool squashfs-tools gperf ^lzma.* libfl-dev ncurses-dev pwgen flex libtinfo5 minicom liblz4-tool libmpfr-dev libssl-dev lib32ncurses5-dev libbz2-dev lib32z1-dev libgmp-dev git libncurses5-dev dpkg-dev libmpc-dev lftp python2-dev python3 rar git-lfs policycoreutils unrar libncurses5 libbz2-1.0 ncftp tree python-all-dev bzip2 bc ftp software-properties-common tar libgl1-mesa-dev texinfo schedtool curl libexpat1-dev libc6-dev-i386 apt-utils cmake g++-multilib build-essential re2c axel maven xsltproc g++ libx11-dev libxml-sax-base-perl gnupg bash
           sudo pip3 install yq
           echo "/usr/lib/ccache" >> $GITHUB_PATH
           echo "USE_CCACHE=1" >> $GITHUB_ENV
           run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Set up the environment Done."

      - name: Set up ccache
        run: |
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          echo "USE_CCACHE=1" >> $GITHUB_ENV
          run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="${{ matrix.version }}: Set up ccache."

      - name: Cache ccache
        uses: actions/cache@v2
        id: cache_ccache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
              ${{ runner.os }}-ccache-
           
      - name: Clone Sources
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x clone.sh
          ./clone.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Cloned sources."

      - name: Add Clang to PATH
        run: |
          echo "${CLANG_PATH}" >> $GITHUB_PATH
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Added Clang to PATH."

      - name: Extract kernel version from Makefile
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x ExVersion.sh
          ./ExVersion.sh "${{ github.workspace }}"
        env:
         VERSION: ${{ matrix.version }}
         TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Extract sources
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x ExSource.sh
          ./ExSource.sh "${{ github.workspace }}" "$VERSION"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Extracted sources."

      - name: Compile kernel
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x build.sh
          ./build.sh "${{ github.workspace }}" "$VERSION"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Compiled kernel."

      - name: Make output directory for kernel
        run: |
          mkdir outw
          mkdir outw/false
          mkdir outw/true
          run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="${{ matrix.version }}: Made output directory for kernel."
          
      - name: Move kernel without KernelSU support to output directory
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x move.sh
          ./move.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Moved kernel without KernelSU support to the output directory."

      - name: Clean build environment
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x clean.sh
          ./clean.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Cleaned build environment."

      - name: Set KERNELSU environment variable to true
        run: |
           echo "KERNELSU=true" >> $GITHUB_ENV
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Set KERNELSU environment variable to true."

      - name: Set KERNELSU_VERSION environment variable
        run: |
          version=$(cat ksu_version.txt)
          echo "KERNELSU_VERSION=$version" >> $GITHUB_ENV
          echo "Read KERNELSU_VERSION: $version"
          run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="${{ matrix.version }}: Set KERNELSU_VERSION environment variable."

      - name: Add KernelSU support to kernel
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x kernelSU.sh
          ./kernelSU.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Added KernelSU support to the kernel."

      - name: Compile kernel with KernelSU support
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x build.sh
          ./build.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Compiled kernel with KernelSU support."

      - name: Move kernel with KernelSU support to output directory
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x move.sh
          ./move.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
           -d text="${{ matrix.version }}: Moved kernel with KernelSU support to the output directory."

      - name: Clone AnyKernel3
        run: |
          VERSION="${{ matrix.version }}"
          chmod +x anykernel.sh
          ./anykernel.sh "${{ github.workspace }}"
        env:
          VERSION: ${{ matrix.version }}
          run: |
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
            -d text="${{ matrix.version }}: Cloned AnyKernel3 repository."

      - name: Set ZIP_NO_KSU and ZIP_KSU environment variables
        run: |
          echo "ZIP_NO_KSU=${{ env.VERSION }}-NoKernelSU.zip" >> $GITHUB_ENV
          echo "ZIP_KSU=${{ env.VERSION }}-KernelSU-$(cat ksu_version.txt).zip" >> $GITHUB_ENV
          run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="${{ matrix.version }}: Set ZIP_NO_KSU and ZIP_KSU environment variables."

      - name: Make AnyKernel3 zip
        run: |
          chmod +x makezip.sh
          ./makezip.sh
          run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="${{ matrix.version }}: Made AnyKernel3 zip."

      - name: Set Build Date # For Build Date Info, currently using Asia/Manila
        run: |
          echo "BUILD_DATE=$(TZ=Asia/Manila date +'%d/%m/%Y')" >> $GITHUB_ENV

      - name: Make a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
             ${{ github.workspace }}/${{ env.ZIP_NO_KSU }}
             ${{ github.workspace }}/${{ env.ZIP_KSU }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Realme 8 (nashc) ${{ matrix.version }} Kernel Release - ${{ env.KERNEL_VERSION }}
          tag_name: ${{ matrix.version }}-${{ github.run_id }}
          body: |
             **Info:**
              - KernelSU Version: ${{ env.KERNELSU_VERSION }}.
              - Kernel Version:
                - ${{ matrix.version }}: ${{ env.KERNEL_VERSION }}
                
             **Source URLs:**
             - ${{ matrix.version }}: ${{ env.KERNEL_URL}}

             **Build Date:**
             - Release Date: ${{ env.BUILD_DATE}}

             **Installation:**
             1. Sideloading in recovery mode.
             2. Refer to our [Mega Guide](https://github.com/driedpampas/realme-8-megaguide) for detailed instructions.

             **Warnings:**
             - Do not use this kernel with the stock firmware of Realme UI; it is only compatible with custom ROMs.

             **Support Group:**
             - Support: Ask In [Realme 8 AOSP](https://t.me/Realme8AOSPGroup) for assistance
          draft: false
          prerelease: false
          run: |
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
            -d text="[Release] Made a release for ${{ matrix.version }}: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ matrix.version }}-${{ github.run_id }}"
      
      - name: Notify on Failure
        if: failure()
        run: |
         curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
         -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
         -d text="[Failure - Run #${{ github.run_number }}] Job failed for ${{ matrix.version }}: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Notify on Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
          -d text="[Success - Run #${{ github.run_number }}] Job succeeded for ${{ matrix.version }}: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          
