name: Trigger Kernel Builder

on:
  push:
    branches:
      - Master
  workflow_dispatch:

jobs:
  trigger_kernel_builder:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete old releases and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ ! -d .git ]; then
            echo "Error: Current directory is not a Git repository."
            exit 1
          fi
          if ! git remote -v | grep -q 'origin'; then
            echo "Error: 'origin' remote is not configured."
            exit 1
          fi

          releases=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases")
          release_ids=$(echo $releases | jq '.[].id')

          for id in $release_ids; do
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$id"
            echo "Deleted release with ID: $id"
          done

          tags=$(git ls-remote --tags origin)
          tag_names=$(echo "$tags" | awk -F/ '{print $3}')

          for tag in $tag_names; do
            git push --delete origin $tag
            echo "Deleted tag: $tag"
          done

      - name: Trigger Kernel Builder Workflow
        run: |
          gh workflow run Kernel-Builder.yml -R ${{ github.repository }} -F trigger_kernel_builder=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
