name: Version Tracker & Deploy

on:
  push:
    branches:
      - Master
  schedule:
    - cron: '0 */06 * * *'
  workflow_dispatch:

jobs:
  Tracker-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new release and trigger build if needed
        id: check_and_trigger_build
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/tiann/KernelSU/releases/latest" | jq -r .tag_name)
          CURRENT_RELEASE=$(cat ksu_version.txt || true)
          echo "Latest release tag version: $LATEST_RELEASE"
          echo "Current version from ksu_version.txt: $CURRENT_RELEASE"
          if [ "$LATEST_RELEASE" != "$CURRENT_RELEASE" ]; then
            echo "LATEST_RELEASE=${LATEST_RELEASE}" >> $GITHUB_ENV
            echo "update_needed=true" >> $GITHUB_ENV
          else
            echo "update_needed=false" >> $GITHUB_ENV
          fi

      - name: Update version and trigger build if needed
        if: env.update_needed == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          echo "${LATEST_RELEASE}" > ksu_version.txt
          if [ "${LATEST_RELEASE}" = "" ]; then
            echo "Version is not updated. No build triggered."
          else
            echo "Version updated. Triggering build..."
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add ksu_version.txt
            git commit -m "Update version to $LATEST_RELEASE"
            git push origin Master
            
            releases=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases")
            release_ids=$(echo $releases | jq '.[].id')

            for id in $release_ids; do
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$id"
              echo "Deleted release with ID: $id"
            done

            tags=$(git ls-remote --tags origin)
            tag_names=$(echo "$tags" | awk -F/ '{print $3}')

            for tag in $tag_names; do
              git push --delete origin $tag
              echo "Deleted tag: $tag"
            done

            gh workflow run Kernel-Builder.yml -R ${{ github.repository }} -F trigger_kernel_builder=true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
