name: Version Tracker & Deploy

on:
  push:
    branches:
      - Master
  schedule:
    - cron: '0 */12 * * *'  # Scheduled to run every 12 hours

jobs:
  check_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new release and trigger build if needed
        id: check_and_trigger_build
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/tiann/KernelSU/releases/latest" | jq -r .tag_name)
          CURRENT_RELEASE=$(cat ksu_version.txt || true)
          if [ "$LATEST_RELEASE" != "$CURRENT_RELEASE" ]; then
            echo "::set-output name=release::$LATEST_RELEASE"
            echo "::set-output name=update_needed::true"
          else
            echo "::set-output name=update_needed::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version and trigger build if needed
        if: steps.check_and_trigger_build.outputs.update_needed == 'true' || github.event_name == 'push'
        run: |
          echo "${{ steps.check_and_trigger_build.outputs.release }}" > ksu_version.txt
          if [ -z "${{ steps.check_and_trigger_build.outputs.release }}" ]; then
            echo "Version is not updated. No build triggered."
          else
            echo "Version updated. Triggering build..."
            # Trigger Kernel Builder Workflow
            gh workflow run Kernel-Builder.yml -R ${{ github.repository }} -F trigger_kernel_builder=true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
